//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StructureCreator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StructureCreator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _00HWD {
            get {
                object obj = ResourceManager.GetObject("_00HWD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _00HWD1 {
            get {
                object obj = ResourceManager.GetObject("_00HWD1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _01_MIP {
            get {
                object obj = ResourceManager.GetObject("_01_MIP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _01_MIP_optimization_01 {
            get {
                object obj = ResourceManager.GetObject("_01_MIP_optimization_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _01_overview1920x1080 {
            get {
                object obj = ResourceManager.GetObject("01-overview1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _01_overview1920x10801 {
            get {
                object obj = ResourceManager.GetObject("01-overview1920x10801", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _02_overview1920x1080_06 {
            get {
                object obj = ResourceManager.GetObject("02-overview1920x1080-06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _02_overview1920x1080_061 {
            get {
                object obj = ResourceManager.GetObject("02-overview1920x1080-061", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _02_overview1920x1080_3 {
            get {
                object obj = ResourceManager.GetObject("02-overview1920x1080-3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _02_overview1920x1080_31 {
            get {
                object obj = ResourceManager.GetObject("02-overview1920x1080-31", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _02_Q_MIP_optimization_01 {
            get {
                object obj = ResourceManager.GetObject("_02_Q_MIP_optimization_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _02_QMIP {
            get {
                object obj = ResourceManager.GetObject("_02_QMIP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _03_new_study_interface {
            get {
                object obj = ResourceManager.GetObject("03-new-study-interface", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _03_new_study_interface1 {
            get {
                object obj = ResourceManager.GetObject("03-new-study-interface1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _03_overview1920x1080 {
            get {
                object obj = ResourceManager.GetObject("03-overview1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _03_overview1920x1080_3 {
            get {
                object obj = ResourceManager.GetObject("03-overview1920x1080-3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _03_SDP {
            get {
                object obj = ResourceManager.GetObject("_03_SDP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _03_SDP_optimization_01 {
            get {
                object obj = ResourceManager.GetObject("_03_SDP_optimization_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _04_PointCloud {
            get {
                object obj = ResourceManager.GetObject("04-PointCloud", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _04_QDP {
            get {
                object obj = ResourceManager.GetObject("_04_QDP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _04_QDP_optimization_01 {
            get {
                object obj = ResourceManager.GetObject("_04_QDP_optimization_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _05_MIP {
            get {
                object obj = ResourceManager.GetObject("_05_MIP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _05_MIP_Eigenvalue_02 {
            get {
                object obj = ResourceManager.GetObject("_05_MIP_Eigenvalue_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _05_Solve {
            get {
                object obj = ResourceManager.GetObject("05-Solve", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _06_QMIP {
            get {
                object obj = ResourceManager.GetObject("_06_QMIP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _06_QMIP_Reconfigurability_02 {
            get {
                object obj = ResourceManager.GetObject("_06_QMIP_Reconfigurability_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _06_Result_01 {
            get {
                object obj = ResourceManager.GetObject("06-Result-01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _07_SDP {
            get {
                object obj = ResourceManager.GetObject("_07_SDP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _07_SDP_Explicit_02 {
            get {
                object obj = ResourceManager.GetObject("_07_SDP_Explicit_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _08_QDP {
            get {
                object obj = ResourceManager.GetObject("_08_QDP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _08_QDP_Elastoplastic_02 {
            get {
                object obj = ResourceManager.GetObject("_08_QDP_Elastoplastic_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;&lt;AddIns&gt;&lt;AddIn name=&quot;ConstructorAddIn&quot; description=&quot;Loaded from a journal file.&quot; assembly=&quot;Samples\V18\SutructureCreator\ConstructorAddIn.dll&quot; typename=&quot;StructureCreator.ConstructorAddIn&quot; host=&quot;SameAppDomain&quot; /&gt;&lt;/AddIns&gt;.
        /// </summary>
        internal static string AddInManifestInfo {
            get {
                return ResourceManager.GetString("AddInManifestInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use an angular body load to apply an angular velocity or angular acceleration to a part. 
        ///
        ///Select faces or edges to define the direction and location references of the applied load. .
        /// </summary>
        internal static string AngularGlobalLoadHint {
            get {
                return ResourceManager.GetString("AngularGlobalLoadHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AngularGlobalLoadImage {
            get {
                object obj = ResourceManager.GetObject("AngularGlobalLoadImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angular Global Load.
        /// </summary>
        internal static string AngularGlobalLoadText {
            get {
                return ResourceManager.GetString("AngularGlobalLoadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bar.
        /// </summary>
        internal static string Bar {
            get {
                return ResourceManager.GetString("Bar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create BCC.
        /// </summary>
        internal static string BccHint {
            get {
                return ResourceManager.GetString("BccHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BccImage {
            get {
                object obj = ResourceManager.GetObject("BccImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BCC.
        /// </summary>
        internal static string BccText {
            get {
                return ResourceManager.GetString("BccText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BearingLoadsCapsule Hint.
        /// </summary>
        internal static string BearingLoadsCapsuleHint {
            get {
                return ResourceManager.GetString("BearingLoadsCapsuleHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BearingLoadsCapsule.
        /// </summary>
        internal static string BearingLoadsCapsuleText {
            get {
                return ResourceManager.GetString("BearingLoadsCapsuleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckForces Hint.
        /// </summary>
        internal static string CheckForcesHint {
            get {
                return ResourceManager.GetString("CheckForcesHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckForces.
        /// </summary>
        internal static string CheckForcesText {
            get {
                return ResourceManager.GetString("CheckForcesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommandCapsule1 Hint.
        /// </summary>
        internal static string CommandCapsule1Hint {
            get {
                return ResourceManager.GetString("CommandCapsule1Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommandCapsule1.
        /// </summary>
        internal static string CommandCapsule1Text {
            get {
                return ResourceManager.GetString("CommandCapsule1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected layer will be filled with Bars.
        /// </summary>
        internal static string CompleteSelectionHint {
            get {
                return ResourceManager.GetString("CompleteSelectionHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CompleteSelectionImage {
            get {
                object obj = ResourceManager.GetObject("CompleteSelectionImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloose Layer.
        /// </summary>
        internal static string CompleteSelectionText {
            get {
                return ResourceManager.GetString("CompleteSelectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applies a fixed, pinned, frictionless, or prescribed displacement constraint to the selected geometry. You can apply constraints to multiple entities you select. .
        /// </summary>
        internal static string ConstraintsHint {
            get {
                return ResourceManager.GetString("ConstraintsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ConstraintsImage {
            get {
                object obj = ResourceManager.GetObject("ConstraintsImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constraints .
        /// </summary>
        internal static string ConstraintsText {
            get {
                return ResourceManager.GetString("ConstraintsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Construct the lattice structure..
        /// </summary>
        internal static string ConstructHint {
            get {
                return ResourceManager.GetString("ConstructHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ConstructImage {
            get {
                object obj = ResourceManager.GetObject("ConstructImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConstrucTOR Add-in.
        /// </summary>
        internal static string ConstructorAddIn {
            get {
                return ResourceManager.GetString("ConstructorAddIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Lattice.
        /// </summary>
        internal static string ConstructText {
            get {
                return ResourceManager.GetString("ConstructText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CPLEXImage {
            get {
                object obj = ResourceManager.GetObject("CPLEXImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use ILOG CPLEX Optimization Studio..
        /// </summary>
        internal static string CplexOptHint {
            get {
                return ResourceManager.GetString("CplexOptHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CPLEXOptImage {
            get {
                object obj = ResourceManager.GetObject("CPLEXOptImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cplex Optimization.
        /// </summary>
        internal static string CplexOptText {
            get {
                return ResourceManager.GetString("CplexOptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates Sample Bars for each Plane.
        /// </summary>
        internal static string CreateBarHint {
            get {
                return ResourceManager.GetString("CreateBarHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CreateBarImage {
            get {
                object obj = ResourceManager.GetObject("CreateBarImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three Bars.
        /// </summary>
        internal static string CreateBarText {
            get {
                return ResourceManager.GetString("CreateBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create assembly space.
        /// </summary>
        internal static string CreateCrossSectionHint {
            get {
                return ResourceManager.GetString("CreateCrossSectionHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Body.
        /// </summary>
        internal static string CreateCrossSectionText {
            get {
                return ResourceManager.GetString("CreateCrossSectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateForce Hint.
        /// </summary>
        internal static string CreateForceHint {
            get {
                return ResourceManager.GetString("CreateForceHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateForce.
        /// </summary>
        internal static string CreateForceText {
            get {
                return ResourceManager.GetString("CreateForceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an linear program based on the simulation study..
        /// </summary>
        internal static string CreateLPHint {
            get {
                return ResourceManager.GetString("CreateLPHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CreateLPImage {
            get {
                object obj = ResourceManager.GetObject("CreateLPImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create LP.
        /// </summary>
        internal static string CreateLPText {
            get {
                return ResourceManager.GetString("CreateLPText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Lines From Point to Point.
        /// </summary>
        internal static string CreatePPBarHint {
            get {
                return ResourceManager.GetString("CreatePPBarHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CreatePPBarImage {
            get {
                object obj = ResourceManager.GetObject("CreatePPBarImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines.
        /// </summary>
        internal static string CreatePPBarText {
            get {
                return ResourceManager.GetString("CreatePPBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CreatePPCylinder {
            get {
                object obj = ResourceManager.GetObject("CreatePPCylinder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CreateQLPHint {
            get {
                return ResourceManager.GetString("CreateQLPHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create QLP.
        /// </summary>
        internal static string CreateQLPText {
            get {
                return ResourceManager.GetString("CreateQLPText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateSCDOC Hint.
        /// </summary>
        internal static string CreateSCDOCHint {
            get {
                return ResourceManager.GetString("CreateSCDOCHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateSCDOC.
        /// </summary>
        internal static string CreateSCDOCText {
            get {
                return ResourceManager.GetString("CreateSCDOCText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postprocess the lattice structure by editing the connections.
        ///
        ///A solid sphere is created at all angled joints. The diameter of the solid sphere is a multiple of the largest bar diameter, which is adjacent to a specific connection joint..
        /// </summary>
        internal static string CreateSpheresHint {
            get {
                return ResourceManager.GetString("CreateSpheresHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CreateSpheresImage {
            get {
                object obj = ResourceManager.GetObject("CreateSpheresImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postprocessing.
        /// </summary>
        internal static string CreateSpheresText {
            get {
                return ResourceManager.GetString("CreateSpheresText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CreateStructureImage {
            get {
                object obj = ResourceManager.GetObject("CreateStructureImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a Bar from Point to Point.
        /// </summary>
        internal static string CylinderPPHint {
            get {
                return ResourceManager.GetString("CylinderPPHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Bar.
        /// </summary>
        internal static string CylinderPPText {
            get {
                return ResourceManager.GetString("CylinderPPText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control or Modify the Data.
        /// </summary>
        internal static string DataControlHint {
            get {
                return ResourceManager.GetString("DataControlHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        internal static string DataControlText {
            get {
                return ResourceManager.GetString("DataControlText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use ILOG CPLEX Optimization Studio..
        /// </summary>
        internal static string DCPLEXHint {
            get {
                return ResourceManager.GetString("DCPLEXHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPLEX Optimization.
        /// </summary>
        internal static string DCPLEXText {
            get {
                return ResourceManager.GetString("DCPLEXText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateStructure Hint.
        /// </summary>
        internal static string DCreateStructureHint {
            get {
                return ResourceManager.GetString("DCreateStructureHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateStructure.
        /// </summary>
        internal static string DCreateStructureText {
            get {
                return ResourceManager.GetString("DCreateStructureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable developer mode for easier acces to settings and fewer restrictions.
        ///
        ///Logfile is available.
        /// </summary>
        internal static string DevelopHint {
            get {
                return ResourceManager.GetString("DevelopHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DevelopImage {
            get {
                object obj = ResourceManager.GetObject("DevelopImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developers mode.
        /// </summary>
        internal static string DevelopText {
            get {
                return ResourceManager.GetString("DevelopText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use GLPK optimization.
        ///
        ///Optionally GLPK can be used for data conversion from GNU MathProg model to CPLEX lp model..
        /// </summary>
        internal static string DGLPSOLHint {
            get {
                return ResourceManager.GetString("DGLPSOLHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GLPK Optimization.
        /// </summary>
        internal static string DGLPSOLText {
            get {
                return ResourceManager.GetString("DGLPSOLText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a mechanical drawing of the lattice structure using a TikZ Library for lattice structures..
        /// </summary>
        internal static string DLatexHint {
            get {
                return ResourceManager.GetString("DLatexHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DLatexImage {
            get {
                object obj = ResourceManager.GetObject("DLatexImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create PDF.
        /// </summary>
        internal static string DLatexText {
            get {
                return ResourceManager.GetString("DLatexText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import a CPLEX  XML solution file into the simulation study..
        /// </summary>
        internal static string DSolFileHint {
            get {
                return ResourceManager.GetString("DSolFileHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPLEX Solution.
        /// </summary>
        internal static string DSolFileText {
            get {
                return ResourceManager.GetString("DSolFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import a CSV file and edit it..
        /// </summary>
        internal static string DTableHint {
            get {
                return ResourceManager.GetString("DTableHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import/Edit CSV.
        /// </summary>
        internal static string DTableText {
            get {
                return ResourceManager.GetString("DTableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dummy1 {
            get {
                object obj = ResourceManager.GetObject("Dummy1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dummy10 {
            get {
                object obj = ResourceManager.GetObject("Dummy10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect joints to adjacent joints..
        /// </summary>
        internal static string Dummy10Hint {
            get {
                return ResourceManager.GetString("Dummy10Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect Joints.
        /// </summary>
        internal static string Dummy10Text {
            get {
                return ResourceManager.GetString("Dummy10Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dummy11 {
            get {
                object obj = ResourceManager.GetObject("Dummy11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dummy2 {
            get {
                object obj = ResourceManager.GetObject("Dummy2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dummy3 {
            get {
                object obj = ResourceManager.GetObject("Dummy3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dummy4 {
            get {
                object obj = ResourceManager.GetObject("Dummy4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dummy5 {
            get {
                object obj = ResourceManager.GetObject("Dummy5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dummy6 {
            get {
                object obj = ResourceManager.GetObject("Dummy6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dummy7 {
            get {
                object obj = ResourceManager.GetObject("Dummy7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dummy8 {
            get {
                object obj = ResourceManager.GetObject("Dummy8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect joints with corrupt connection..
        /// </summary>
        internal static string Dummy8Hint {
            get {
                return ResourceManager.GetString("Dummy8Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect Joints.
        /// </summary>
        internal static string Dummy8Text {
            get {
                return ResourceManager.GetString("Dummy8Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dummy9 {
            get {
                object obj = ResourceManager.GetObject("Dummy9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a specific joint..
        /// </summary>
        internal static string Dummy9Hint {
            get {
                return ResourceManager.GetString("Dummy9Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Joint.
        /// </summary>
        internal static string Dummy9Text {
            get {
                return ResourceManager.GetString("Dummy9Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify the magnitude and direction of gravity. To specify the gravity direction either specify a vector, enter an angle, or select a geometric reference..
        /// </summary>
        internal static string EditGravityHint {
            get {
                return ResourceManager.GetString("EditGravityHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EditGravityImage {
            get {
                object obj = ResourceManager.GetObject("EditGravityImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Gravity.
        /// </summary>
        internal static string EditGravityText {
            get {
                return ResourceManager.GetString("EditGravityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditStabs Hint.
        /// </summary>
        internal static string EditStabsHint {
            get {
                return ResourceManager.GetString("EditStabsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditStabs.
        /// </summary>
        internal static string EditStabsText {
            get {
                return ResourceManager.GetString("EditStabsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ExportImage {
            get {
                object obj = ResourceManager.GetObject("ExportImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Quality and Export Step File.
        /// </summary>
        internal static string ExportStepHint {
            get {
                return ResourceManager.GetString("ExportStepHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STEP.
        /// </summary>
        internal static string ExportStepText {
            get {
                return ResourceManager.GetString("ExportStepText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Quality and Export STL File.
        /// </summary>
        internal static string ExportStlHint {
            get {
                return ResourceManager.GetString("ExportStlHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STL.
        /// </summary>
        internal static string ExportStlText {
            get {
                return ResourceManager.GetString("ExportStlText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ex-Functions.
        /// </summary>
        internal static string ExtraGroupText {
            get {
                return ResourceManager.GetString("ExtraGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create FCC.
        /// </summary>
        internal static string FccHint {
            get {
                return ResourceManager.GetString("FccHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FccImage {
            get {
                object obj = ResourceManager.GetObject("FccImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FCC.
        /// </summary>
        internal static string FccText {
            get {
                return ResourceManager.GetString("FccText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Figure0001 {
            get {
                object obj = ResourceManager.GetObject("Figure0001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string FirstGroupText {
            get {
                return ResourceManager.GetString("FirstGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structures.
        /// </summary>
        internal static string ForthGroupText {
            get {
                return ResourceManager.GetString("ForthGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GLPSOLImage {
            get {
                object obj = ResourceManager.GetObject("GLPSOLImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use GLPK optimization.
        ///
        ///Optionally GLPK can be used for data conversion from GNU MathProg model to CPLEX lp model..
        /// </summary>
        internal static string GlpsolOptHint {
            get {
                return ResourceManager.GetString("GlpsolOptHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GLPK Optimization.
        /// </summary>
        internal static string GlpsolOptText {
            get {
                return ResourceManager.GetString("GlpsolOptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GroundImage {
            get {
                object obj = ResourceManager.GetObject("GroundImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a Ground Structure.
        /// </summary>
        internal static string GroundStructureHint {
            get {
                return ResourceManager.GetString("GroundStructureHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ground.
        /// </summary>
        internal static string GroundStructureText {
            get {
                return ResourceManager.GetString("GroundStructureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_connections_32x32 {
            get {
                object obj = ResourceManager.GetObject("icon_connections_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_mesh_by_id_32x32 {
            get {
                object obj = ResourceManager.GetObject("icon_mesh_by_id_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_orientation_pan_down_32x32 {
            get {
                object obj = ResourceManager.GetObject("icon_orientation_pan_down_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_project_32x32 {
            get {
                object obj = ResourceManager.GetObject("icon_project_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_solution_probe_adjustment_32x32 {
            get {
                object obj = ResourceManager.GetObject("icon_solution_probe_adjustment_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_solution_probe_beam_tool_32x32 {
            get {
                object obj = ResourceManager.GetObject("icon_solution_probe_beam_tool_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_solution_results_lattice_density_beta_32x32 {
            get {
                object obj = ResourceManager.GetObject("icon_solution_results_lattice_density_beta_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose file to import.
        /// </summary>
        internal static string ImportDataHint {
            get {
                return ResourceManager.GetString("ImportDataHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImportDataImage {
            get {
                object obj = ResourceManager.GetObject("ImportDataImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string ImportDataText {
            get {
                return ResourceManager.GetString("ImportDataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a mechanical drawing of the lattice structure using a TikZ Library for lattice structures..
        /// </summary>
        internal static string LatexHint {
            get {
                return ResourceManager.GetString("LatexHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create PDF.
        /// </summary>
        internal static string LatexText {
            get {
                return ResourceManager.GetString("LatexText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap leftArrow {
            get {
                object obj = ResourceManager.GetObject("leftArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a linear body load to apply a linear acceleration to a part.
        ///
        ///Specify the acceleration direction by selecting a face normal to the direction of the load or by specifying an angle or a vector..
        /// </summary>
        internal static string LinearGlobalLoadHint {
            get {
                return ResourceManager.GetString("LinearGlobalLoadHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LinearGlobalLoadImage {
            get {
                object obj = ResourceManager.GetObject("LinearGlobalLoadImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear Global Load.
        /// </summary>
        internal static string LinearGlobalLoadText {
            get {
                return ResourceManager.GetString("LinearGlobalLoadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View and modify study attributes (loads and constraints) in one place..
        /// </summary>
        internal static string LoadCaseAttributesHint {
            get {
                return ResourceManager.GetString("LoadCaseAttributesHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LoadCaseAttributesImage {
            get {
                object obj = ResourceManager.GetObject("LoadCaseAttributesImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Case Attributes.
        /// </summary>
        internal static string LoadCaseAttributesText {
            get {
                return ResourceManager.GetString("LoadCaseAttributesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  TEST123 .
        /// </summary>
        internal static string LoadsHint {
            get {
                return ResourceManager.GetString("LoadsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LoadsImage {
            get {
                object obj = ResourceManager.GetObject("LoadsImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loads.
        /// </summary>
        internal static string LoadsText {
            get {
                return ResourceManager.GetString("LoadsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Hint.
        /// </summary>
        internal static string ManageHint {
            get {
                return ResourceManager.GetString("ManageHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ManageImage {
            get {
                object obj = ResourceManager.GetObject("ManageImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ManageMaterialImage {
            get {
                object obj = ResourceManager.GetObject("ManageMaterialImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the Material Browser to manage material libraries, identify favorites, modify properties, and create new materials..
        /// </summary>
        internal static string ManagePhysicalMaterialsHint {
            get {
                return ResourceManager.GetString("ManagePhysicalMaterialsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Physical Materials.
        /// </summary>
        internal static string ManagePhysicalMaterialsText {
            get {
                return ResourceManager.GetString("ManagePhysicalMaterialsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        internal static string ManageText {
            get {
                return ResourceManager.GetString("ManageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays material properties.
        /// </summary>
        internal static string MaterialPropertiesHint {
            get {
                return ResourceManager.GetString("MaterialPropertiesHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Properties.
        /// </summary>
        internal static string MaterialPropertiesText {
            get {
                return ResourceManager.GetString("MaterialPropertiesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MaterialPropImage {
            get {
                object obj = ResourceManager.GetObject("MaterialPropImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View the original physical materials for the active simulation study, and assign new study materials as needed. 
        ///
        ///Use Study Materials to assign the correct matrials to your components. This is important for simulating an accurate representation of the physical model..
        /// </summary>
        internal static string MaterialsHint {
            get {
                return ResourceManager.GetString("MaterialsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MaterialsImage {
            get {
                object obj = ResourceManager.GetObject("MaterialsImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materials.
        /// </summary>
        internal static string MaterialsText {
            get {
                return ResourceManager.GetString("MaterialsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill Gaps between Bars.
        /// </summary>
        internal static string MergeFacesHint {
            get {
                return ResourceManager.GetString("MergeFacesHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge.
        /// </summary>
        internal static string MergeFacesText {
            get {
                return ResourceManager.GetString("MergeFacesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MergetImage {
            get {
                object obj = ResourceManager.GetObject("MergetImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewStudyGroup Hint.
        /// </summary>
        internal static string NewStudyGroupHint {
            get {
                return ResourceManager.GetString("NewStudyGroupHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewStudyGroup.
        /// </summary>
        internal static string NewStudyGroupText {
            get {
                return ResourceManager.GetString("NewStudyGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Simulation Study
        ///
        ///Create a new simulation study.
        ///
        ///Choose a study type, and optionally change study settings for example study name..
        /// </summary>
        internal static string NewStudyHint {
            get {
                return ResourceManager.GetString("NewStudyHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NewStudyImage {
            get {
                object obj = ResourceManager.GetObject("NewStudyImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string NewStudyText {
            get {
                return ResourceManager.GetString("NewStudyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applies bearing loads to a selected point. .
        /// </summary>
        internal static string OpenBearingLoadsHint {
            get {
                return ResourceManager.GetString("OpenBearingLoadsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OpenBearingLoadsImage {
            get {
                object obj = ResourceManager.GetObject("OpenBearingLoadsImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearing Loads.
        /// </summary>
        internal static string OpenBearingLoadsText {
            get {
                return ResourceManager.GetString("OpenBearingLoadsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate a lattice structure based on a CPLEX XML solution file..
        /// </summary>
        internal static string OpenConstructFormHint {
            get {
                return ResourceManager.GetString("OpenConstructFormHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Lattice Structure.
        /// </summary>
        internal static string OpenConstructFormText {
            get {
                return ResourceManager.GetString("OpenConstructFormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenStructuralLoads Hint.
        /// </summary>
        internal static string OpenStructuralLoadsHint {
            get {
                return ResourceManager.GetString("OpenStructuralLoadsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenStructuralLoads.
        /// </summary>
        internal static string OpenStructuralLoadsText {
            get {
                return ResourceManager.GetString("OpenStructuralLoadsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap overview1258x717_04 {
            get {
                object obj = ResourceManager.GetObject("overview1258x717-04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap overview1258x717_05 {
            get {
                object obj = ResourceManager.GetObject("overview1258x717-05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User defines a Structure Dimensions.
        /// </summary>
        internal static string PointCloudHint {
            get {
                return ResourceManager.GetString("PointCloudHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PointCloudImage {
            get {
                object obj = ResourceManager.GetObject("PointCloudImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        internal static string PointCloudText {
            get {
                return ResourceManager.GetString("PointCloudText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Auto Point Mass to represent the effects of an existing component in the simulation model. This is useful for simplifying the simulation model.
        ///
        ///To assign a point mass, select the geometric item on which the point mass acts. .
        /// </summary>
        internal static string PointMassAutoHint {
            get {
                return ResourceManager.GetString("PointMassAutoHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PointMassAutoImage {
            get {
                object obj = ResourceManager.GetObject("PointMassAutoImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point Mass (Auto).
        /// </summary>
        internal static string PointMassAutoText {
            get {
                return ResourceManager.GetString("PointMassAutoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Manual Point Mass to represent the effects of a component or mass not included in the simulation model. Such a component should have very little effect on the model stiffness.
        ///
        ///After specifying the location on the model, specify its mass. Point masses are useful for reducing model complexity. .
        /// </summary>
        internal static string PointMassManualHint {
            get {
                return ResourceManager.GetString("PointMassManualHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PointMassManualImage {
            get {
                object obj = ResourceManager.GetObject("PointMassManualImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point Mass (Manual).
        /// </summary>
        internal static string PointMassManualText {
            get {
                return ResourceManager.GetString("PointMassManualText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point to Point Bar.
        /// </summary>
        internal static string PPBar {
            get {
                return ResourceManager.GetString("PPBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point to Point Cylinder.
        /// </summary>
        internal static string PPCylinder {
            get {
                return ResourceManager.GetString("PPCylinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReadBearingLoad Hint.
        /// </summary>
        internal static string ReadBearingLoadHint {
            get {
                return ResourceManager.GetString("ReadBearingLoadHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReadBearingLoad.
        /// </summary>
        internal static string ReadBearingLoadText {
            get {
                return ResourceManager.GetString("ReadBearingLoadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReadData Hint.
        /// </summary>
        internal static string ReadDataHint {
            get {
                return ResourceManager.GetString("ReadDataHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ReadDataImage {
            get {
                object obj = ResourceManager.GetObject("ReadDataImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReadData.
        /// </summary>
        internal static string ReadDataText {
            get {
                return ResourceManager.GetString("ReadDataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReadForcePoint Hint.
        /// </summary>
        internal static string ReadForcePointHint {
            get {
                return ResourceManager.GetString("ReadForcePointHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReadForcePoint.
        /// </summary>
        internal static string ReadForcePointText {
            get {
                return ResourceManager.GetString("ReadForcePointText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReadPoint Hint.
        /// </summary>
        internal static string ReadPointHint {
            get {
                return ResourceManager.GetString("ReadPointHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ReadPointImage {
            get {
                object obj = ResourceManager.GetObject("ReadPointImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReadPoint.
        /// </summary>
        internal static string ReadPointText {
            get {
                return ResourceManager.GetString("ReadPointText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReadWindow Hint.
        /// </summary>
        internal static string ReadWindowHint {
            get {
                return ResourceManager.GetString("ReadWindowHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ReadWindowImage {
            get {
                object obj = ResourceManager.GetObject("ReadWindowImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReadWindow.
        /// </summary>
        internal static string ReadWindowText {
            get {
                return ResourceManager.GetString("ReadWindowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View the results of the simulation study..
        /// </summary>
        internal static string ResultFilesHint {
            get {
                return ResourceManager.GetString("ResultFilesHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ResultFilesImage {
            get {
                object obj = ResourceManager.GetObject("ResultFilesImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result Files.
        /// </summary>
        internal static string ResultFilesText {
            get {
                return ResourceManager.GetString("ResultFilesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the results of the simulation study.
        ///
        ///CAD, PDF and CSV is available..
        /// </summary>
        internal static string ResultsHint {
            get {
                return ResourceManager.GetString("ResultsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ResultsImage {
            get {
                object obj = ResourceManager.GetObject("ResultsImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        internal static string ResultsText {
            get {
                return ResourceManager.GetString("ResultsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;customUI
        ///  xmlns=&quot;http://schemas.spaceclaim.com/customui&quot;
        ///  xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///  xsi:schemaLocation=&quot;http://schemas.spaceclaim.com/customui http://schemas.spaceclaim.com/customui/SpaceClaimCustomUI.V19.xsd&quot;&gt;
        ///	&lt;ribbon&gt;
        ///		&lt;tabs&gt;
        ///			&lt;tab id=&quot;ConstructorAddIn.C#.V19.RibbonTab&quot; command=&quot;ConstructorAddIn.C#.V19.RibbonTab&quot;&gt;
        ///        &lt;!-- 
        ///					For the &apos;tab&apos; and &apos;group&apos; elements, you can either specify a &apos;label&apos; attribute, or you can [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Ribbon {
            get {
                return ResourceManager.GetString("Ribbon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RibbonTabCapsule Hint.
        /// </summary>
        internal static string RibbonTabCapsuleHint {
            get {
                return ResourceManager.GetString("RibbonTabCapsuleHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RibbonTabCapsule.
        /// </summary>
        internal static string RibbonTabCapsuleText {
            get {
                return ResourceManager.GetString("RibbonTabCapsuleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConstrucTOR.
        /// </summary>
        internal static string RibbonTabText {
            get {
                return ResourceManager.GetString("RibbonTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rightArrow {
            get {
                object obj = ResourceManager.GetObject("rightArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string SecondGroupText {
            get {
                return ResourceManager.GetString("SecondGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings Hint.
        /// </summary>
        internal static string SettingsHint {
            get {
                return ResourceManager.GetString("SettingsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsText {
            get {
                return ResourceManager.GetString("SettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simplify Hint.
        /// </summary>
        internal static string SimplifyHint {
            get {
                return ResourceManager.GetString("SimplifyHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SimplifyImage {
            get {
                object obj = ResourceManager.GetObject("SimplifyImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simplify.
        /// </summary>
        internal static string SimplifyText {
            get {
                return ResourceManager.GetString("SimplifyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SolFileImage {
            get {
                object obj = ResourceManager.GetObject("SolFileImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SolImportForm Hint.
        /// </summary>
        internal static string SolImportFormHint {
            get {
                return ResourceManager.GetString("SolImportFormHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SolImportForm.
        /// </summary>
        internal static string SolImportFormText {
            get {
                return ResourceManager.GetString("SolImportFormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import a CPLEX  XML solution file into the simulation study..
        /// </summary>
        internal static string SolImportHint {
            get {
                return ResourceManager.GetString("SolImportHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPLEX Solution.
        /// </summary>
        internal static string SolImportText {
            get {
                return ResourceManager.GetString("SolImportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use algorithm-driven optimization to generate and optimize lattice structures. .
        /// </summary>
        internal static string SolveHint {
            get {
                return ResourceManager.GetString("SolveHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SolveImage {
            get {
                object obj = ResourceManager.GetObject("SolveImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built.
        /// </summary>
        internal static string SolveText {
            get {
                return ResourceManager.GetString("SolveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now User may create a StrucTOR.
        /// </summary>
        internal static string StrucTorHint {
            get {
                return ResourceManager.GetString("StrucTorHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StrucTorImage {
            get {
                object obj = ResourceManager.GetObject("StrucTorImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StrucTOR.
        /// </summary>
        internal static string StrucTorText {
            get {
                return ResourceManager.GetString("StrucTorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string StructuralConstraints2DHint {
            get {
                return ResourceManager.GetString("StructuralConstraints2DHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create 2D Surface.
        /// </summary>
        internal static string StructuralConstraints2DText {
            get {
                return ResourceManager.GetString("StructuralConstraints2DText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new assembly space
        ///
        ///The assembly space is defined by a fixed point cloud.
        ///
        ///.
        /// </summary>
        internal static string StructuralConstraintsHint {
            get {
                return ResourceManager.GetString("StructuralConstraintsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StructuralConstraintsImage {
            get {
                object obj = ResourceManager.GetObject("StructuralConstraintsImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create 3D Volume.
        /// </summary>
        internal static string StructuralConstraintsText {
            get {
                return ResourceManager.GetString("StructuralConstraintsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applies structural loads to a selected point. .
        /// </summary>
        internal static string StructuralLoadsHint {
            get {
                return ResourceManager.GetString("StructuralLoadsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StructuralLoadsImage {
            get {
                object obj = ResourceManager.GetObject("StructuralLoadsImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structural Load.
        /// </summary>
        internal static string StructuralLoadsText {
            get {
                return ResourceManager.GetString("StructuralLoadsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View the original physical materials for the active simulation study, and assign new study materials as needed. 
        ///
        ///Use Study Materials to assign the correct matrials to your components. This is important for simulating an accurate representation of the physical model..
        /// </summary>
        internal static string StudyMaterialsHint {
            get {
                return ResourceManager.GetString("StudyMaterialsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study Materials.
        /// </summary>
        internal static string StudyMaterialsText {
            get {
                return ResourceManager.GetString("StudyMaterialsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TableImage {
            get {
                object obj = ResourceManager.GetObject("TableImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifications and Repair.
        /// </summary>
        internal static string ThirdGroupText {
            get {
                return ResourceManager.GetString("ThirdGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables you to unsuppress the gravity load. 
        ///
        ///By default, gravity acts in the negative Y direction. A symbol at the model origin indicates the direction of gravity. To modify the gravity magnitude or direction, use the Edit Gravity command..
        /// </summary>
        internal static string ToggleGravityOnHint {
            get {
                return ResourceManager.GetString("ToggleGravityOnHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ToggleGravityOnImage {
            get {
                object obj = ResourceManager.GetObject("ToggleGravityOnImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Gravity On.
        /// </summary>
        internal static string ToggleGravityOnText {
            get {
                return ResourceManager.GetString("ToggleGravityOnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id, start Node, end Node, Diameter, Force.
        /// </summary>
        internal static string Trial {
            get {
                return ResourceManager.GetString("Trial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WErstelleArrow Hint.
        /// </summary>
        internal static string WErstelleArrowHint {
            get {
                return ResourceManager.GetString("WErstelleArrowHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WErstelleArrow.
        /// </summary>
        internal static string WErstelleArrowText {
            get {
                return ResourceManager.GetString("WErstelleArrowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WErstelleKugel Hint.
        /// </summary>
        internal static string WErstelleKugelHint {
            get {
                return ResourceManager.GetString("WErstelleKugelHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WErstelleKugel.
        /// </summary>
        internal static string WErstelleKugelText {
            get {
                return ResourceManager.GetString("WErstelleKugelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WriteLP Hint.
        /// </summary>
        internal static string WriteLPHint {
            get {
                return ResourceManager.GetString("WriteLPHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WriteLPImage {
            get {
                object obj = ResourceManager.GetObject("WriteLPImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WriteLP.
        /// </summary>
        internal static string WriteLPText {
            get {
                return ResourceManager.GetString("WriteLPText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YASOL Optimization.
        /// </summary>
        internal static string YasolOptText {
            get {
                return ResourceManager.GetString("YasolOptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string YasolSolHint {
            get {
                return ResourceManager.GetString("YasolSolHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yasol Solution.
        /// </summary>
        internal static string YasolSolText {
            get {
                return ResourceManager.GetString("YasolSolText", resourceCulture);
            }
        }
    }
}
